spring:
  config:
    activate:
      on-profile: test
    
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/

jwt:
  secret: v9yBEHMcQfTjWnZr4u7xACFJaNdRgUkXp2s5v8yBEGKbPeShVmYq3tv9yBEHMcQfTjdsakjdsajqqhfhfehfhdsd
  access-token-validity: 3600000       # 1시간 (60 * 60 * 1000)
  refresh-token-validity: 86400000 # 24시간 (60 * 60 * 24 * 1000)